	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar tu progreso?$"

gText_AlreadySavedFile::
	.string "Hay una partida guardada.\n"
	.string "¿Sobreescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó el juego.$"

gText_DifferentSaveFile::
	.string "¡PELIGRO!\p"
	.string "Ya hay otra partida guardada\n"
	.string "Si guardas ahora, se perderá el\n"
	.string "progreso de la partida anterior\p"
	.string "¿Estás de acuerdo con guardar ahora\n"
	.string "y borrar la partida anterior?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Por favor, cambía la batería\n"
	.string "de soporte.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "No apagues la consola.$"
