@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "¿Oh? ¿Querías hacer {POKEBLOCK}S\n"
	.string "con este anciano?$"

BerryBlender_Text_Excellent:
	.string "¡Exelente!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Oh…\n"
	.string "Pusiste triste a este pobre abuelito…$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "¿Sabes como se hace un {POKEBLOCK}?$"

BerryBlender_Text_LetsBerryBlender:
	.string "¡Comencemos entonces!\p"
	.string "¡Encedamos el Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Déjame explicarte, entonces.\p"
	.string "No te preocupes, es bastante simple.\p"
	.string "Cuando la flecha del Licuabayas pase\n"
	.string "por tu marcador, presiona el Botón A.\p"
	.string "Es todo lo que hay que hacer.\n"
	.string "Verás lo fácil que es cuando lo intentes.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "¿Oh?\n"
	.string "¿No tienes Bayas?\p"
	.string "Si no tienes ninguna Baya,\n"
	.string "No puedes hacer PokéCubos.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "No te preocupes\p"
	.string "Resulta que hoy tengo Bayas de sobra\n"
	.string "y puedo prestarte una.\p"
	.string "De esa forma, podremos hacer PokéCubos juntos\n"
	.string "usando el Licuabayas.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "Si tuviera Bayas de sobra,\n"
	.string "Te daría algunas…\p"
	.string "Pero no tengo ninguna ahora.\n"
	.string "Tendremos que hacerlo en otra ocación.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Tu Tubo PokéCubos está lleno.\p"
	.string "Usa algunos PokéCubos primero\n"
	.string "y ven a verme.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Pero no tienes un Tubo PokéCubos.\p"
	.string "Consigue uno y ven a verme.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "¡Comencemos con el Licuabayas!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "Me pregunto que clase de {POKEBLOCK} saldrá.\n"
	.string "¡Es tan emocionante!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "¡Hola! ¿Quíeres crear unos ?\n"
	.string "PokéCubos con nosotros?$"

BerryBlender_Text_Okay:
	.string "¡De acuerdo!$"

BerryBlender_Text_ThatsTooBad:
	.string "Que mal…\p"
	.string "No te preocupes, estaremos por\n"
	.string "aqui siempre que lo necesites.$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Por supuesto, ya sabes como hacer\n"
	.string "PokéCubos, ¿no es así?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "¡Comencemos entonces!\p"
	.string "¡Encedamos el Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "¡Bien!\n"
	.string "¡Dehja que te explique!\p"
	.string "Cuando la flecha llegue a tu\n"
	.string "indicador solo debes presionar\l"
	.string "el Botón A.\p"
	.string "Es todo lo que necesitas saber.\n"
	.string "Fácil, ¿No crees?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Oh, pero si no parece…\n"
	.string "que tengas ninguna Baya.\p"
	.string "No puedes hacer PokéCubos sin\n"
	.string "Bayas…\p"
	.string "Ven a vernos cuando consigas\n"
	.string "unas cuantas Bayas.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Espera un segundo…\n"
	.string "Tu Tubo PokéCubos está lleno.\p"
	.string "Consigue algunos PokéCubos y luego\n"
	.string "ven a vernos.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Espera un segundo…\n"
	.string "No tienes un Tubo PokéCubos.\p"
	.string "Deberías conseguir uno y\n"
	.string "volver más tarde.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "¡Buenas! ¿Tienes ganas de hacern"
	.string "PokéCubos con nosotros?$"

BerryBlender_Text_OhDear:
	.string "¡Oh, no!$"

BerryBlender_Text_LeftUsInShock:
	.string "Ah…\p"
	.string "¡Me has dejado sin palabras!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "¿Ya sabes como hacer\n"
	.string "PokéCubos, no es así?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "¡Bien cariño!\n"
	.string "¡Encendamos el Licuabayas!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "¡Veo!\p"
	.string "Déjame explicarlo entonces.\p"
	.string "Cuando la flecha apunte a tu cursor\n"
	.string "presiona el Botón A.\p"
	.string "Es todo lo que necesitas.\n"
	.string "Es muy simple, ¿Verdad?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "No tienes ninguna Baya,\n"
	.string "¿No es así?\p"
	.string "Si no tienes Bayas,\n"
	.string "no puedes hacer PokéCubos.\p"
	.string "Siempre hacemos PokéCubos aqui,\n"
	.string "asi que juntémosnos cuando\l"
	.string "tengas un par de Bayas.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Tu Tubo PokéCubos está lleno,\n"
	.string "o eso parece.\p"
	.string "Usa algunos PokéCubos y luego\n"
	.string "ven a vernos.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "No tienes un Tubo PokéCubos\n"
	.string "aún, por lo que veo.\p"
	.string "Consigue uno primero y luego\n"
	.string "ven a verme.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "¡Hoy será el gran día para\n"
	.string "un núevo record en el Licuabayas!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "¡Cariño!\n"
	.string "Parece que sabes licuar Bayas.\l"
	.string "¿Te nos unes al grupo?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "Haré PokéCubos deliciosos y haré\n"
	.string "a mis Pokémon más dulces.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "Se harán PokéCubos con amigos \n"
	.string "con Bayas en el Licuabayas.\p"
	.string "¿Quíeres guardar el juego antes\n"
	.string "de licuar bayas con amigos?$"

BerryBlender_Text_SearchingForFriends:
	.string "Buscando Amigos…\n"
	.string "… … Botón B: Cancelar$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} se conectó.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} y {STR_VAR_2} se conectaron.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2}, y\n"
	.string "{STR_VAR_3} se conectaron.$"

BerryBlender_Text_NoBerriesLink:
	.string "No tienes Bayas.\n"
	.string "No puedes usar el Licuabayas.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Tu Tubo PokéCubos está lleno.\n"
	.string "No puedes usar el Licuabayas.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "No tienes un Tubo PokéCubos.\n"
	.string "No puedes usar el Licuabayas.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "Amo hacer PokéCubos.\p"
	.string "Siempre llevo unas Bayas conmigo.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Si quieres, puedes unirte a\n"
	.string "crear PokéCubos con nosotros\l"
	.string "en el Licuabayas, ¿Que dices?.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "¿Oh?\n"
	.string "¿No tienes Bayas?\p"
	.string "No podrás hacer nada, ¿no es así?\p"
	.string "Si no te importa, puedo darte\n"
	.string "una de mis Bayas.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "La usaremos para hacer juntos\n"
	.string "PokéCubos en el Licuabayas.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "¿Oh?\n"
	.string "¿No tienes Bayas?\p"
	.string "Si me sobraran, felizmente te\n"
	.string "daría una…\p"
	.string "Pero no tengo ninguna.\n"
	.string "¡Perdón!$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_UseBerryBlender2
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_UseBerryBlender3
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_BlendWithBlendMaster
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, NO
	call_if_eq BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, TRUE
	goto_if_eq BerryBlender_EventScript_ExpertMPlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_fastest_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_LinkBlenderSaveGame
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryDoLinkBlender
	compare VAR_RESULT, NO
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	compare VAR_RESULT, TRUE
	goto_if_eq BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_SpawnLinkPartners
	compare VAR_RESULT, LINKUP_SOMEONE_NOT_READY
	goto_if_eq BerryBlender_EventScript_CloseLinkNotReady
	compare VAR_RESULT, LINKUP_DIFF_SELECTIONS
	goto_if_eq BerryBlender_EventScript_CloseLinkDifferentSelections
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_CloseLink
	compare VAR_RESULT, LINKUP_CONNECTION_ERROR
	goto_if_eq BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238 
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
	goto_if_eq BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
	goto_if_eq BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
